server:
  port: ${PORT:8081}

spring:
  application:
    name: Producto
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/productos_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

logging:
  level:
    cl.duocuc.Producto: INFO
